accounts/urls.py
from django.urls import path
from . import views
#from accounts.views import ResetPasswordView
#from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('signup',views.signup_view,name='signup'),
    path('password_reset', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path('',blog_view,name='index'),
    path('<int:pid>/',blog_single,name='single'),
    path('category/<str:cat_name>',blog_view,name='category'),
    path('tag/<str:tag_name>',blog_view,name='tag'),
    path('author/<str:author_username>',blog_view,name='author'),
    path('search/',blog_search,name='search'),
    path("rss/feed/", LatestEntriesFeed()),

    #path('test',test,name='test'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import  BlogSitemap
from django.views.generic.base import TemplateView
from django.urls import re_path

sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap

}
urlpatterns = [
    
    path('admin/', admin.site.urls),
    #path('url address','view')
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.xml', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')), 
]

if settings.MAINTENANCE_MODE:
        urlpatterns.insert(0, re_path(r'^', TemplateView.as_view(template_name='Coming_Soon.html')))

urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import (PasswordChangeForm,ReadOnlyPasswordHashField)
from django.core.exceptions import ValidationError
# from .models import User


class LoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False)

class SignUpForm(UserCreationForm):
    email=forms.EmailField()

    class Meta:
        model=User
        fields=('username','email','password1','password2')


class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput({'placeholder': "Current password", 'id': "old_password"}))
    new_password1 = forms.CharField(widget=forms.PasswordInput({'placeholder': "New password", 'id': "new_password1"}))
    new_password2 = forms.CharField(widget=forms.PasswordInput({'placeholder': "Confirm password", 'id': "new_password2"}))

    def clean_old_password(self):
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise ValidationError("Your current password was entered incorrectly. please try again")
        return old_password
class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'is_active', 'is_superuser','is_staff')

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import SignUpForm
#from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import (PasswordResetCompleteView,PasswordResetConfirmView,PasswordResetDoneView,PasswordResetView)
# Create your views here.
def login_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            input = request.POST['username']
            try:
                username = User.objects.get(email=input).username
            except User.DoesNotExist:
                username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                messages.add_message(request,messages.SUCCESS,'Login was successful')

                return redirect('/')
            else:
                messages.add_message(request,messages.ERROR,'The desired person was not found')
                return render(request, "accounts/login.html")
        form = AuthenticationForm()
        context = {'form': form}
        return render(request,'accounts/login.html',context)
    else:
        return redirect('/')
@login_required
def logout_view(request):
    logout(request)
    return redirect('/')


def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form=SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('/')
        form=SignUpForm()
        context = {'form': form}
        return render (request,'accounts/signup.html',context)
    return redirect('/')
'''
class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'registration/password_reset.html'
    email_template_name = 'registration/password_reset_email.html'
    subject_template_name = 'registration/password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('registration:password_reset_done')
'''
class PasswordReset(PasswordResetView):
    template_name="registration/password_reset_form.html"
    success_url=reverse_lazy("accounts:password_reset_done")

class PasswordResetDone(PasswordResetDoneView):
    template_name="registration/password_reset_done.html"
    success_url=reverse_lazy("accounts:password_reset_confirm")

class PasswordResetConfirm(PasswordResetConfirmView):
    template_name="registration/password_reset_confirm.html"
    success_url=reverse_lazy("accounts:password_reset_complete")

class PasswordResetComplete(PasswordResetCompleteView):
    template_name="registration/password_reset_complete.html"

templates/accounts/login.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>Login</title>

   

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{%static 'css/signin.css'%}">
  

  </head>

  <body class="text-center">
    
    <form class="form-signin" method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %} 
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Login</h1>
      <input type="text" class="form-control" name="username" placeholder="username or email" required autofocus>
      <label for="email" class="form-label">Username or Email</label>

      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Login in</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>

    </form>
    <a href="{%url 'accounts:signup'%}" class="link-secondary text-decoration-none">Create new account</a>
    ,
    <a href="{% url 'accounts:password_reset'%}" class="link-secondary text-decoration-none">Forgot password</a>
    {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
    {% endfor %}
    {% endif %}

  </body>
</html>

templates/accounts/signup.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>Sign up</title>

   
 
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{%static 'css/signin.css'%}">

  </head>

  <body class="text-center">
    <form class="form-signin" method="post" action="{% url 'accounts:signup' %}">
      {% csrf_token %}
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Sign up</h1>
      
      <label for="inputUsername" class="sr-only">Username</label>
      <input type="text" name="username" class="form-control" placeholder="Username" required autofocus>
      
      <label for="inputEmail" class="sr-only">Email</label>
      <input type="email" name="email" class="form-control" placeholder="Email" required autofocus>
      
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password1" class="form-control" placeholder="Password" required>
      
      <label for="inputPassword" class="sr-only">Confirm Password</label>
      <input type="password" name="password2" class="form-control" placeholder="Confirm Password" required>
      
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>