blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path('',blog_view,name='index'),
    path('<int:pid>/',blog_single,name='single'),
    path('category/<str:cat_name>',blog_view,name='category'),
    path('tag/<str:tag_name>',blog_view,name='tag'),
    path('author/<str:author_username>',blog_view,name='author'),
    path('search/',blog_search,name='search'),
    path("rss/feed/", LatestEntriesFeed()),

    #path('test',test,name='test'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import  BlogSitemap
from django.views.generic.base import TemplateView
from django.urls import re_path

sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap

}
urlpatterns = [
    
    path('admin/', admin.site.urls),
    #path('url address','view')
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.xml', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')), 
]

if settings.MAINTENANCE_MODE:
        urlpatterns.insert(0, re_path(r'^', TemplateView.as_view(template_name='Coming_Soon.html')))

urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *
app_name='website'
urlpatterns = [
    path('',index_views,name='index'),
    path('about/',about_views,name='about'),
    path('contact/',contact_views,name='contact'),
    path('test/',test_views,name='test'),
    #path('newsletter',newsletter_views,name='newsletter')
] 

website/models.py
from django.db import models

# Create your models here.
class Cantact(models.Model):
    name=models.CharField(max_length=225)
    email=models.EmailField()
    subject=models.CharField(null=True,blank=True,max_length=225)
    message=models.TextField()
    created_date=models.DateField(auto_now_add=True)
    updated_date=models.DateField(auto_now=True)
    class Meta():
        ordering = ('created_date',)
    def __str__(self):
        return '{} {}'.format(self.name, self.id)

website/forms.py
from django import forms
from website.models import Cantact
from captcha.fields import CaptchaField

class NameForm(forms.Form):
    name = forms.CharField(max_length=225)
    email = forms.EmailField()
    subject = forms.CharField(max_length=225)
    message = forms.CharField(widget=forms.Textarea)

class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Cantact
        fields = '__all__'

website/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,QueryDict
from website.forms import ContactForm
from django.contrib import messages

# Create your views here.
def index_views (request):
    return render(request,'website/index.html')
def about_views (request):
    return render(request,'website/about.html')
def contact_views (request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            new_name = form.save(commit=False)
            new_name.name = "Unknown"
            new_name.save()
            form.save_m2m()
           
            messages.add_message(request,messages.SUCCESS,'your ticket submitted successfully')
        else:
            messages.add_message(request,messages.ERROR,'your ticket didnt submitted')
        
    form=ContactForm()
    return render(request,'website/contact.html',{'form':form})
        

def test_views(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('done')
        else:
            return HttpResponse('not valid')
    form=ContactForm()
    return render(request,'test.html',{'form':form})

templates/website/about.html
{% extends 'base.html'%}
{%load static%}
{%block content%}
	<aside id="ftco-hero" class="js-fullheight">
		<div class="flexslider js-fullheight">
			<ul class="slides">
			<li style="background-image: url('http://127.0.0.1:8000/static/images/hero_1.jpg');">
		   		<div class="overlay-gradient"></div>
		   		<div class="container">
		   			<div class="row">
			   			<div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
			   				<div class="slider-text-inner">
			   					<h1><strong>About Legal Office</strong></h1>
								
			   				</div>
			   			</div>
			   		</div>
		   		</div>
		   	</li>
		  	</ul>
	  	</div>
	</aside>

	<div class="site-section">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<img src="{%static 'images/hero_1.jpg' %}" alt="Image" class="img-responsive img-rounded">
				</div>
				<div class="col-md-1"></div>
				<div class="col-md-5">
					<h2>Welcome To Our Legal Office</h2>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts. </p>
					<p><a href="#" class="btn btn-primary">Read More</a></p>
				</div>
			</div>
		</div>
	</div>

	<div id="ftco-about">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center ftco-heading">
					<h2>Our Attorneys</h2>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 col-sm-4 text-center animate-box" data-animate-effect="fadeIn">
					<div class="ftco-staff">
						<img src="{%static 'images/user-3.jpg' %}" alt="Template">
						<h3>Joyce Kroell</h3>
						<strong class="role">Counsel</strong>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						<ul class="ftco-social-icons">
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 text-center animate-box" data-animate-effect="fadeIn">
					<div class="ftco-staff">
						<img src="{%static 'images/user-1.jpg' %}" alt="Template">
						<h3>James Garett</h3>
						<strong class="role">Head of International Practice</strong>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						<ul class="ftco-social-icons">
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 text-center animate-box" data-animate-effect="fadeIn">
					<div class="ftco-staff">
						<img src="{%static 'images/user-2.jpg' %}" alt="Template">
						<h3>Peter Washington</h3>
						<strong class="role">Managing Partner, Attorney</strong>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						<ul class="ftco-social-icons">
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>



	<div id="ftco-practice">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center ftco-heading">
					<h2>Practice Area</h2>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-courthouse"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Real Estate Law</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-padlock"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Insurance Law</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-folder"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Business Law</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-handcuffs"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Personal Injury</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-handcuffs"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Medical Neglegence</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-libra"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Criminal Defense</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-12 text-center animate-box">
					<p><a class="btn btn-primary btn-lg btn-learn" href="#">View More <i class="icon-arrow-right"></i></a></p>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/website/contact.html
{% extends 'base.html'%}
{%load static%}
{%block content%}


	<aside id="ftco-hero" class=" 'js-fullheight">
		<div class="flexslider js-fullheight">
			<ul class="slides">
		   	<li style="background-image: url(http://127.0.0.1:8000/static/images/hero_1.jpg);">
		   		<div class="overlay-gradient"></div>
		   		<div class="container">
		   			<div class="row">
			   			<div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
			   				<div class="slider-text-inner">
			   					<h1><strong>Contact Us</strong></h1>
			   				</div>
			   			</div>
			   		</div>
		   		</div>
		   	</li>
		  	</ul>
	  	</div>
	</aside>

	<div id="ftco-contact">
		<div class="container">
			<div class="row">
				<div class="col-md-5 col-md-push-1 animate-box">
					
					<div class="colorlib-contact-info">
						<h3>Contact Information</h3>
						<ul>
							<li class="address">198 West 21th Street, <br> Suite 721 New York NY 10016</li>
							<li class="phone"><a href="tel://1234567920">+ 1235 2355 98</a></li>
							<li class="email"><a href="mailto:info@yoursite.com">info@yoursite.com</a></li>
							<li class="url"><a href="#">lawfirm.com</a></li>
						</ul>
					</div>

				</div>
				<div class="col-md-6 animate-box">
					<h3>Send A Message</h3>
					<form action="{% url 'website:contact' %}" method="post">
						{% csrf_token %}

						<div class="row form-group">
							<div class="col-md-6">
								<!-- <label for="fname">First Name</label> -->
								<input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Enter your name'" class="form-control"
								required="" type="text">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">

								<input name="email" placeholder="Enter email address"
								pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'"
								class="form-control" required="" type="email">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<!-- <label for="subject">Subject</label> -->
								<input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Enter subject'" class="form-control"
								 type="text">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<!-- <label for="message">Message</label> -->
								<textarea class="common-textarea form-control" name="message" placeholder="Enter Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'"
								required=""></textarea>							</div>
						</div>
						{{form.captcha}}
						<div class="form-group">
							<input type="submit" value="Send Message" class="btn btn-primary">
						</div>

					</form>		
				</div>
			</div>
			{% if form.errors %}
			<div class="alert alert-error">
			  <h4>Please fix the following errors</h4>
			  <ul>
				{% for field in form %}
				  {% if field.errors %}
					{% for error in field.errors %}
					  <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
					{% endfor %}
				  {% endif %}
				{% endfor %}
			  </ul>
			  {% if form.non_field_errors %}
				{{ form.non_field_errors }}
			  {% endif %}
			</div>
		  {% endif %}
		</div>
	</div>
	<div id="map" class="colorlib-map"></div>
{% endblock %}

templates/website/index.html
{% extends 'base.html' %}
{% load static %}
{% load website_tags %}
{% block content %}


	<aside id="ftco-hero" class="js-fullheight">
		<div class="flexslider js-fullheight">
			<ul class="slides">
		   	<li style="background-image: url(static/images/hero_1.jpg);">
		   		<div class="overlay-gradient"></div>
		   		<div class="container">
		   			<div class="row">
			   			<div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
			   				<div class="slider-text-inner">
			   					<h1><strong>Defend Your Constitutional Right with Legal Help</strong></h1>
			   				</div>
			   			</div>
			   		</div>
		   		</div>
		   	</li>
		   	<li style="background-image: url(static/images/hero_3.jpg);">
		   		<div class="overlay-gradient"></div>
		   		<div class="container">
		   			<div class="row">
			   			<div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
			   				<div class="slider-text-inner">
			   					<h1><strong>Defend Your Constitutional Right with Legal Help</strong></h1>
			   				</div>
			   			</div>
			   		</div>
		   		</div>
		   	</li>
		   	<li style="background-image: url(static/images/hero_2.jpg);">
		   		<div class="overlay-gradient"></div>
		   		<div class="container">
		   			<div class="row">
			   			<div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
			   				<div class="slider-text-inner">
			   					<h1><strong>Defend Your Constitutional Right with Legal Help</strong></h1>
									
			   				</div>
			   			</div>
			   		</div>
		   		</div>
		   	</li>		   	
		  	</ul>
	  	</div>
	</aside>

	<div class="site-section">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<img src="{%static 'images/hero_1.jpg' %}" alt="Image" class="img-responsive img-rounded">
				</div>
				<div class="col-md-1"></div>
				<div class="col-md-5">
					<h2>Welcome To Our Legal Office</h2>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts. </p>
					<p><a href="#" class="btn btn-primary">Read More</a></p>
				</div>
			</div>
		</div>
	</div>

	<div class="ftco-practice">
		<div class="container">
			
			<div class="row">
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-courthouse"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Real Estate Law</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-padlock"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Insurance Law</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-folder"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Business Law</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


	

	<div id="ftco-counter" class="ftco-counters" data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-3 text-center animate-box">
					<span class="icon"><i class="flaticon-lawyer-1"></i></span>
					<span class="ftco-counter js-counter" data-from="0" data-to="2893" data-speed="5000" data-refresh-interval="50"></span>
					<span class="ftco-counter-label">Our Lawyer</span>
				</div>
				<div class="col-md-3 text-center animate-box">
					<span class="icon"><i class="flaticon-courthouse"></i></span>
					<span class="ftco-counter js-counter" data-from="0" data-to="291" data-speed="5000" data-refresh-interval="50"></span>
					<span class="ftco-counter-label">Our Clients</span>
				</div>
				<div class="col-md-3 text-center animate-box">
					<span class="icon"><i class="flaticon-libra"></i></span>
					<span class="ftco-counter js-counter" data-from="0" data-to="952" data-speed="5000" data-refresh-interval="50"></span>
					<span class="ftco-counter-label">Successful Case</span>
				</div>
				<div class="col-md-3 text-center animate-box">
					<span class="icon"><i class="flaticon-police-badge"></i></span>
					<span class="ftco-counter js-counter" data-from="0" data-to="1921" data-speed="5000" data-refresh-interval="50"></span>
					<span class="ftco-counter-label">Honor &amp; Awards</span>
				</div>
			</div>
		</div>
	</div>

	<div id="ftco-content">
		<div class="video ftco-video" style="background-image: url(static/images/blog-4.jpg);">
			<a href="https://vimeo.com/channels/staffpicks/93951774" class="popup-vimeo"><i class="icon-play"></i></a>
			<div class="overlay"></div>
		</div>
		<div class="choose animate-box">
			<div class="ftco-heading">
				<h2>Far far away, behind the word mountains</h2>
				<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts far from the countries Vokalia and Consonantia, there live the blind texts. </p>
				<p><a href="#" class="btn btn-primary">Learn More</a></p>
			</div>
			
		</div>
	</div>

	<div class="ftco-practice">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center ftco-heading">
					<h2>Practice Area</h2>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-courthouse"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Real Estate Law</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-padlock"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Insurance Law</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-folder"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Business Law</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-handcuffs"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Personal Injury</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-handcuffs"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Medical Neglegence</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="services">
						<span class="icon">
							<i class="flaticon-libra"></i>
						</span>
						<div class="desc">
							<h3><a href="#">Criminal Defense</a></h3>
							<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
						</div>
					</div>
				</div>
				<div class="col-md-12 text-center animate-box">
					<p><a class="btn btn-primary btn-lg btn-learn" href="#">View More <i class="icon-arrow-right"></i></a></p>
				</div>
			</div>
		</div>
	</div>


	

	
    <!---
	<div id="ftco-blog">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center ftco-heading">
					<h2>Recent Post</h2>
					<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 col-lg-4">
					<div class="blog-featured animate-box">
						<a href="blog-single.html"><img class="img-responsive img-rounded" src="{%static 'images/blog-1.jpg' %}" alt=""></a>
						<h2><a href="blog-single.html">Far from the countries Vokalia and Consonantia</a></h2>
						<p class="meta"><span>Jan 5, 2017</span> | <span>3 Comments</span></p>
						<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however</p>
					</div>
				</div>
			</div>
		</div>
	</div>
    -->

	<div id="ftco-about">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center ftco-heading">
					<h2>Our Attorneys</h2>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 col-sm-4 text-center animate-box" data-animate-effect="fadeIn">
					<div class="ftco-staff">
						<img src="{%static 'images/user-3.jpg' %}" alt="Template">
						<h3>Joyce Kroell</h3>
						<strong class="role">Counsel</strong>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						<ul class="ftco-social-icons">
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 text-center animate-box" data-animate-effect="fadeIn">
					<div class="ftco-staff">
						<img src="{%static 'images/user-1.jpg' %}" alt="Template">
						<h3>James Garett</h3>
						<strong class="role">Head of International Practice</strong>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						<ul class="ftco-social-icons">
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 text-center animate-box" data-animate-effect="fadeIn">
					<div class="ftco-staff">
						<img src="{%static 'images/user-2.jpg' %}" alt="Template">
						<h3>Peter Washington</h3>
						<strong class="role">Managing Partner, Attorney</strong>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						<ul class="ftco-social-icons">
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	{% blogposts %}

{% endblock %}

templates/website/website-latest-post.html
{% load static %}
{% load website_tags %}
<div id="ftco-blog">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center ftco-heading">
                <h2>Recent Post</h2>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however</p>
            </div>
        </div>
        {% for post in posts %}
        <div class="row">
            <div class="col-md-6 col-lg-4">
                <div class="blog-featured animate-box">
                    <a href="{% url 'blog:single' post.id %}"><img class="img-responsive img-rounded" src="{{post.image.url}}" alt=""></a>
                    <div class="details">
						<div class="tags">
							<ul>
								{%for cat in post.category.all%}
								
									<a href='{% url "blog:category" cat_name=cat.name %}'>{{cat.name}}</a> {% if not forloop.last %} ,{% endif %}
								
								{%endfor%}
		
							</ul>
						</div>
                    <h2><a href="{% url 'blog:single' post.id %}">{{post.title}}</a></h2>
                    <p class="meta"><span>{{post.published_date|date:'d M Y'}}</span></p>
                    <p>{{post.content|truncatewords:10}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>