blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path('',blog_view,name='index'),
    path('<int:pid>/',blog_single,name='single'),
    path('category/<str:cat_name>',blog_view,name='category'),
    path('tag/<str:tag_name>',blog_view,name='tag'),
    path('author/<str:author_username>',blog_view,name='author'),
    path('search/',blog_search,name='search'),
    path("rss/feed/", LatestEntriesFeed()),

    #path('test',test,name='test'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import  BlogSitemap
from django.views.generic.base import TemplateView
from django.urls import re_path

sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap

}
urlpatterns = [
    
    path('admin/', admin.site.urls),
    #path('url address','view')
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.xml', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')), 
]

if settings.MAINTENANCE_MODE:
        urlpatterns.insert(0, re_path(r'^', TemplateView.as_view(template_name='Coming_Soon.html')))

urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=225)
    def __str__(self):
        return self.name
class Post(models.Model):
    id = models.IntegerField(primary_key=True)
    image=models.ImageField(upload_to='blog/',default='blog/blog-1.jpg')
    author=models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    title=models.CharField(max_length=225)
    content=models.TextField()
    tags = TaggableManager()
    category=models.ManyToManyField(category)
    counted_views= models.IntegerField(default=0)
    status=models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date=models.DateTimeField(null=True)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)#2024-03-30 11:10:56.530638

    class Meta:
        ordering=['-published_date']
    def __str__(self):
        return '{}-{}'.format(self.title, self.id)
    #def snippets(self):
        #return self.content[100] +'...' 

    def get_absolute_url(self):
        return reverse('blog:single',kwargs={'pid':self.id})
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    name = models.CharField(max_length=225)
    email = models.EmailField()
    subject = models.CharField(max_length=225)
    message = models.TextField()
    approved = models.BooleanField(default=False) 
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm):
    #captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = ['post','name', 'email', 'subject','message']

blog/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Post,Comment
from django.utils import timezone
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from blog.forms import CommentForm
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.
def blog_view(request,**kwargs):
    posts=Post.objects.filter(published_date__lte=timezone.now(),status=1).order_by('published_date')
    if kwargs.get('cat_name')!=None:
        posts=posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_username')!=None:
        posts=posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('tag_name')!=None:
        posts=posts.filter(tags__name=kwargs['tag_name'])
    posts=Paginator(posts,3)
    try:
        page_number=request.GET.get('page')
        posts=posts.get_page(page_number)
    except PageNotAnInteger:
        posts=posts.get_page(1)
    except EmptyPage:
        posts=posts.get_page(1)
    
    context={'posts':posts}
    return render(request,'blog/blog-home.html',context)
def blog_single(request,pid):
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'your comment submited successfully')
        else:
           messages.add_message(request,messages.ERROR,'your comment didnt submiter')
                    
    post=get_object_or_404(Post,id=pid,status=1,published_date__lte=timezone.now())
    post.counted_views=post.counted_views+1
    post.save()
    next_post = Post.objects.filter(id__gt=pid,published_date__lte=timezone.now(),status=1).last()
    previous_post = Post.objects.filter(id__lt=pid,published_date__lte=timezone.now(),status=1).first()
    if post.login_require:
        if request.user.is_authenticated:
        
            comments = Comment.objects.filter(post=post.id,approved=True)
            form = CommentForm()
            context={'post':post,
                    'next_post':next_post,
                    'previous_post':previous_post,
                    'comments':comments,
                    'form':form,}
            return render(request,'blog/blog-single.html',context)
        else:
            return HttpResponseRedirect(reverse('accounts:login'))
    else:
        comments = Comment.objects.filter(post=post.id,approved=True)
        form = CommentForm()
        context={'post':post,
                'next_post':next_post,
                'previous_post':previous_post,
                'comments':comments,
                'form':form,}
        return render(request,'blog/blog-single.html',context)
        
        
#def test(request):
    #posts=get_object_or_404(Post,id=pid)
    #context={'posts':posts}
    #return render(request,'test.html')
def blog_search(request):

    posts=Post.objects.filter(published_date__lte=timezone.now(),status=1)
    if request.method == "GET":
        s = request.GET.get('s')
        posts=posts.filter(content__contains=s)
    context={'posts':posts}
    return render(request,'blog/blog-home.html',context)

templates/blog/blog-home.html
{%extends 'base.html'%}
{%load static%}
{% load blog_tags %}
{%block content%}
	<aside id="ftco-hero" class="js-fullheight">
		<div class="flexslider js-fullheight">
			<ul class="slides">
		   	<li style="background-image: url('http://127.0.0.1:8000/static/images/hero_1.jpg');">
		   		<div class="overlay-gradient"></div>
		   		<div class="container">
		   			<div class="row">
			   			<div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
			   				<div class="slider-text-inner">
			   					<h1><strong>Our Blog</strong></h1>

			   				</div>
			   			</div>
			   		</div>
		   		</div>
		   	</li>
		  	</ul>
	  	</div>
		 
	</aside>
     
   
	<div id="ftco-blog">
		
		<div class="container">
			
			<div class="row">
				<div class="col-md-6 col-lg-4">
					{% for post in posts %}
					<div class="blog-featured blog-entry animate-box">
						<a href="{% url 'blog:single' post.id %}"><img class="img-responsive img-rounded" src={{post.image.url}} alt=""></a>
						<h2><a href="{% url 'blog:single' post.id %}">{{post.title}}</a></h2>
						{%for cat in post.category.all%}
						<li><a href='{% url "blog:category" cat_name=cat.name %}'>{{cat.name}}</a>{% if not forloop.last %} {% endif %}</li>
						{%endfor%}
						<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}} Views</a> <span
							class="lnr lnr-eye"></span></p>
						<p class="meta"><span>{{post.published_date|date:'d M Y'}}</span> | <span> {% comments_count post.id %} Comments</span></p>
						<p>{{post.content|truncatewords:10}}</p>
					</div>
					{% endfor %}
				</div>
			</div>
			
	
	
			<nav class="blog-pagination justify-content-center d-flex">		
				<ul class="pagination">
					{% if posts.has_previous %}
					<li class="page-item">
						<a href="?page={{ page_obj.previous_page_number }}" class="caption">
							<span>&#8617;</span>		
						</a>
					</li>
					{% endif %}
					{% for i in posts.paginator.page_range %}
					{% if posts.number == i %}
						<li class="page-item active"><a href="?page={{i}}">{{i}}</a></li>
					{% else %}
						<li><a href="?page={{i}}">{{i}}</a></li>
					{% endif %}
					{% endfor %}
					{% if posts.has_next %}
					<li>
						<a href="?page={{ posts.next_page_number }}" class="caption">
							<span>&#8618;</span>	
						</a>
					</li>
					{% endif %}
				</ul>
			</nav>
		</div>
    </div>

{% endblock %}

templates/blog/blog-popular-post.html
{% load static %}
{% load humanize %}
<div class="single-sidebar-widget popular-post-widget">
    
    <h4 class="popular-title">Popular Posts</h4>
    <div class="popular-post-list">
        {%for post in posts%}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <p><img src="{{post.image.url}}" alt="Image" class="img-responsive"></p>
            </div>
            <div class="details">
                <a href="{% url 'blog:single' post.id %}">
                    <h6>{{post.title}}</h6>
                </a>
                <p>{{post.published_date|naturaltime}}</p>
            </div>
        </div>
        {%endfor%}
    </div>
</div>

templates/blog/blog-post-categories.html
{% load static %}
<div class="sidebar-box">
    <div class="categories">
      <h3>Categories</h3>
      {% for name,count in categories.items %}
      <li><a href="{% url 'blog:category' cat_name=name %}">{{name}} <span>{{count}}</span></a></li>
      {% endfor %}
    </div>
  </div>

templates/blog/blog-search.html
{% load static %}
<div class="col-md-4 sidebar">
    <div class="sidebar-box">
        <form class="search-form" action="{% url 'blog:search' %}" method="get">
            <div class="form-group">
                <span class="icon fa fa-search"></span>
        <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''"
            onblur="this.placeholder = 'Search Posts'">
 
    </form>
</div>

templates/blog/blog-single.html
{% extends 'base.html'%}
{%load static%}
{% load blog_tags %}
{% load humanize %}
{%block content%}
	<aside id="ftco-hero" class="js-fullheight">
		<div class="flexslider js-fullheight">
			<ul class="slides">
		   	<li style="background-image: url('http://127.0.0.1:8000/static/images/hero_1.jpg');">
		   		<div class="overlay-gradient"></div>
		   		<div class="container">
		   			<div class="row">
			   			<div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
			   				<div class="slider-text-inner">
								
			   					<h1><strong>{{post.title}}</strong></h1>
			   				</div>
			   			</div>
			   		</div>
		   		</div>
		   	</li>
		  	</ul>
	  	</div>
	</aside>

	<div id="ftco-blog">
		
		<div>
      <div class="container">
        <div class="row">
		    <div>
				<p><img src="{{post.image.url}}" alt="Image" class="img-responsive"></p>
			</div>
			<p><a href="#">{{post.published_date|date:'d M Y'}}</a> | <a href="#">{{post.counted_views}} Views</a></p>
        
          <div class="col-md-8 blog-content">
            <p class="lead">{{post.content|safe}}</p>
            <!---
            <blockquote><p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p></blockquote>
            <div class="pt-5">		  
              <p>Categories:  <a href="#">Design</a>,<a href="#">Events</a> 
			   Tags: {% for tag in post.tags.all %}<li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>{% endfor %}
			-->
            
		    <div class="navigation-area">
				<div class="row">
					<div
						class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
						<div class="thumb">
						{%if previous_post%}
							<a href="{% url 'blog:single' previous_post.id %}"><p><img src="{{previous_post.image.url}}" alt="Image" class="img-responsive"></p></a>
						</div>
						
						
						<div class="detials">
							<p>Prev Post</p>
							<a href="{% url 'blog:single' previous_post.id %}">
								<h4>{{previous_post.title}}</h4>
							</a>
						{%endif%}
						</div>
					</div>
					<div
					{%if next_post%}
						class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
						
							<div class="thumb">
								<a href="{% url 'blog:single' next_post.id %}"><img src="{{next_post.image.url}}" alt="Image" class="img-responsive"></a>
							</div>
							<div class="detials">
							<p>Next Post</p>
							<a href="{% url 'blog:single' next_post.id %}">
								<h4>{{next_post.title}}</h4>
							</a>
					</div>
						
					
					{%endif%}	
					</div>
				</div>
			</div>

            <div class="pt-5">
              <h3 class="mb-5"> {{ comments|length }} Comments</h3>
			  <div class="comment-form-wrap pt-5">
                <h3 class="mb-5">Leave a comment</h3>
				<form method="post" action="{% url 'blog:single' pid=post.id %}">
				{% csrf_token %}
				  <input type="hidden" name="post" value="{{post.id}}">
                  {% if request.user.is_authenticated %}
				  <input type="hidden" name="name" value={{request.user.first_name}}>
						<input type="hidden" name="email" value={{request.user.email}}>
				  {% else %}
                  <div class="form-group">
					<input type="text" class="form-control" name="name" placeholder="Enter Name"
					onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
                  </div>
                  <div class="form-group">
					<input type="email" class="form-control" name="email" placeholder="Enter email address"
					onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
                  </div>
				  {% endif %}
				  <div class="form-group">
					<input type="text" class="form-control" name="subject" placeholder="Subject"
						onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
				  </div>

				  <div class="form-group">
					<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
						onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
						required=""></textarea>
				  </div>
                  <div class="form-group">
					<button type="submit" class="primary-btn text-uppercase">Post Comment</button>
				  </div>

                </form>
              </div>
			  {% for comment in comments %}
              <ul class="comment-list">
                <li class="comment">
                  <div class="vcard bio">
                    <img src="{% static 'images/person_2.jpg' %}" alt="Image">
                  </div>
                  <div class="comment-body">
                    <h3>{{comment.name}}</h3>
                    <div class="meta">{{comment.created_date|naturalday}}</div>
                    <p>{{comment.message}}</p>
                  </div>
                </li>
              </ul>
              <!-- END comment-list -->
              {% endfor %}
            </div>

          </div>
          {% include 'blog/blog-search.html' %}
		  {% postcategories %}
		  {% include 'blog/blog-tag.html' %}
			
	
            <div class="sidebar-box">
			  <!---
              <p><img src="{% static 'images/user-1.jpg' %}" alt="Image" class="img-responsive"></p>
			  -->
              <h3 class="text-black">Author</h3>
              <p>{{post.author.get_full_name}}</p>

			  {% latestposts %}
          </div>
        </div>
      </div>
    </div>

	</div>
{% endblock %}

	

templates/blog/blog-tag.html
{% load static %}
<div class="sidebar-box">
    <div class="categories">
      <h3>Tag Clouds</h3>
      <ul>
        {% for tag in post.tags.all %}
        <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
        {% endfor %}
    </ul>
    </div>
  </div>