accounts/urls.py
from django.urls import path
from . import views
#from accounts.views import ResetPasswordView
#from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('signup',views.signup_view,name='signup'),
    path('password_reset', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path('',blog_view,name='index'),
    path('<int:pid>/',blog_single,name='single'),
    path('category/<str:cat_name>',blog_view,name='category'),
    path('tag/<str:tag_name>',blog_view,name='tag'),
    path('author/<str:author_username>',blog_view,name='author'),
    path('search/',blog_search,name='search'),
    path("rss/feed/", LatestEntriesFeed()),

    #path('test',test,name='test'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import  BlogSitemap
from django.views.generic.base import TemplateView
from django.urls import re_path

sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap

}
urlpatterns = [
    
    path('admin/', admin.site.urls),
    #path('url address','view')
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.xml', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')), 
]

if settings.MAINTENANCE_MODE:
        urlpatterns.insert(0, re_path(r'^', TemplateView.as_view(template_name='Coming_Soon.html')))

urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *
app_name='website'
urlpatterns = [
    path('',index_views,name='index'),
    path('about/',about_views,name='about'),
    path('contact/',contact_views,name='contact'),
    path('test/',test_views,name='test'),
    #path('newsletter',newsletter_views,name='newsletter')
] 

templates/Coming_Soon.html
<div class="bgimg">
    <div class="topleft">
      <p>Logo</p>
    </div>
    <div class="middle">
      <h1>COMING SOON</h1>
      <hr>
      <p>35 days</p>
    </div>
    <div class="bottomleft">
      <p>Some text</p>
    </div>
  </div>

templates/base.html
{% load static %}
{% load compress %}
<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Lawmaker &mdash; Website Template by Colorlib</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />
	<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700" rel="stylesheet">
    {% compress css %}
	
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css'%}">
	<!-- Flaticons  -->
	<link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css'%}">
    {% endcompress %}
	<!-- Modernizr JS -->
	{% compress js %}
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	{% endcompress %}
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->
	</head>
	<body>
		
		<div class="ftco-loader"></div>
		
		<div id="page">
		<nav class="ftco-nav" role="navigation">
			<ul>
				{% if request.user.is_authenticated %}
				<li><a href="#">logged in as {{request.user.username}}</a></li>
				<li><a href="{% url 'accounts:logout' %}">Logout</a></li>
				{% else %}
				<li><a href="{% url 'accounts:login' %}">Login</a></li>
				<li><a href="{% url 'accounts:signup' %}">Signup</a></li>
				{% endif %}
			</ul>
			<div class="top-menu">
				<div class="container">
					<div class="row">
						<div class="col-md-2">
							<div id="ftco-logo"><a href="{%url 'website:index'%}">Lawmaker</a></div>
						</div>
						<div class="col-md-10 text-right menu-1">
							<ul>
								<li><a href="{%url 'website:index'%}">Home</a></li>
			
								<li class="has-dropdown">
									<a href="{%url 'blog:index'%}">Blog</a>
								</li>
								<li><a href="{%url 'website:about'%}">About</a></li>
								<li><a href="{%url 'website:contact'%}">Contact</a></li>
							</ul>
						</div>
					</div>
					
				</div>
			</div>
		</nav>
    {% block content %}
 
    {% endblock %}
	{% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
    {% endfor %}
    {% endif %}
<footer id="ftco-footer" role="contentinfo">
	<div class="container">
		<div class="row row-pb-md">
			<div class="col-md-3 ftco-widget">
				<h4>Lawfirm</h4>
				<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
			</div>
			<div class="col-md-3 col-md-push-1">
				<h4>Navigation</h4>
				<ul class="ftco-footer-links">
					<li><a href="{%url 'website:index'%}">Home</a></li>
					<li><a href="{%url 'blog:index' %}">Blog</a></li>
					<li><a href="{%url 'website:about'%}">About us</a></li>
				</ul>
			</div>

			<div class="col-md-3 col-md-push-1">
				<h4>Contact Information</h4>
				<ul class="ftco-footer-links">
					<li>198 West 21th Street, <br> Suite 721 New York NY 10016</li>
					<li><a href="tel://1234567920">+ 1235 2355 98</a></li>
					<li><a href="mailto:info@yoursite.com">info@yoursite.com</a></li>
				</ul>
			</div>

			<div class="col-md-3 col-md-push-1">
				<h4>Opening Hours</h4>
				<ul class="ftco-footer-links">
					<li>Mon - Thu: 9:00 - 21 00</li>
					<li>Fri 8:00 - 21 00</li>
					<li>Sat 9:30 - 15: 00</li>
				</ul>
			</div>

		</div>

		<div class="row copyright">
			<div class="col-md-12 text-center">
			<p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        		Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
        	<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        	</p>
			<p>
				<ul class="ftco-social-icons">
				<li><a href="#"><i class="icon-twitter"></i></a></li>
				<li><a href="#"><i class="icon-facebook"></i></a></li>
				<li><a href="#"><i class="icon-linkedin"></i></a></li>
				<li><a href="#"><i class="icon-dribbble"></i></a></li>
				</ul>
			</p>
		    </div>
		</div>

	</div>
</footer>


	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	{% compress js %}
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Stellar Parallax -->
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<!-- Carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
	<!-- countTo -->
	<script src="{% static 'js/jquery.countTo.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/magnific-popup-options.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>
    {% endcompress %}
	 <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

	</body>
</html>